### ISSUE TITLE
Custom sintax colors

### ISSUE THREAD

**Issue by nsanzumuhire** [dannymcgee/vscode-ng-html#1]
This Extention saved me, but how can we customize sintax colors?

**Comment by dannymcgee** [comment]
Awesome, I'm glad you're finding it useful!

There are a number of guides out there for creating custom syntax/color themes for VS Code, here are links to a few:
* [Create a new Color Theme](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme) (VS Code)
* [Creating a VS Code Theme](https://css-tricks.com/creating-a-vs-code-theme/) (CSS-Tricks)
* [How to write a Visual Studio Code color theme from scratch](https://medium.com/@caludio/how-to-write-a-visual-studio-code-color-theme-from-scratch-7ccb7e5da2aa) (Medium/Claudio Cicali)

If you're already using a custom theme from the Marketplace and you just want to edit it, you can create a quick and dirty "fork" of sorts by finding the theme in your extensions folder (on Windows it's `C:/Users/[username]/.vscode/extensions/`), changing the "name" and "publisher" values in `package.json` (so your changes don't get overwritten if the theme updates), and adding some custom scope definitions like this:

```javascript
{
  "name": "[Friendly Scope Name Here]",
  "scope": [ "tm.scope.name.here" ],
  "settings": {
    "foreground": "#FFFFFF"
  }
}
```

You can inspect scope names by entering `Developer: Inspect TM Scopes` in VS Code's command palette and clicking on the token whose color you want to change.

Here's a list of the custom scopes added by this extension:
* `punctuation.definition.ng-attribute-name.begin.html`
* `punctuation.definition.ng-attribute-name.end.html`
* `entity.other.attribute-name.ng-attribute-name.html`
* `keyword.control.ng-control.html`

If you need more specific scope names than that, I could probably be persuaded to make them more granular at some point.

Closing this now since it's not really a bug report, but feel free to add a comment if you have any other questions!
